import {
  createAgentPayCheckoutHandler,
  merchantManifest,
  type MerchantCheckoutResult,
  type MerchantProduct,
} from "@agentpay/merchant-sdk";

import { env } from "@/lib/env";
import type { SignedQuote } from "@/lib/quote";

/**
 * The only bridge between AutoParts and AgentPay.
 *
 * Everything crosses this file through the published `@agentpay/merchant-sdk`
 * package and AgentPay's public registry HTTP endpoints. There is no import
 * from the AgentPay repository, no shared database, and no internal module.
 */

export type MerchantIdentity = {
  merchantId: string;
  merchantName: string;
  registryUrl: string;
  origin: string;
};

export function merchantIdentity(): MerchantIdentity {
  const configuration = env();
  return {
    merchantId: configuration.AGENTPAY_MERCHANT_ID,
    merchantName: configuration.AGENTPAY_MERCHANT_NAME,
    registryUrl: configuration.AGENTPAY_REGISTRY_URL,
    origin: configuration.AUTOPARTS_PUBLIC_ORIGIN,
  };
}

/** Path the SDK advertises as this store's AgentPay checkout endpoint. */
export const CHECKOUT_PATH = "/v1/agents-pay/orders/verification";

/**
 * Discovery document, generated by the SDK so the store cannot drift away from
 * the `agentpay/1.0` contract.
 */
export function discoveryDocument(identity: MerchantIdentity = merchantIdentity()) {
  return merchantManifest({
    origin: identity.origin,
    merchantId: identity.merchantId,
    merchantName: identity.merchantName,
    checkoutPath: CHECKOUT_PATH,
    registryUrl: identity.registryUrl,
  });
}

/**
 * A quote is the purchasable unit AutoParts asks AgentPay to authorise.
 *
 * The SDK's checkout contract resolves a single product id at a single price,
 * so the store presents the signed quote as that unit: its id, its AgentPay
 * category, and its exact total. The mandate is therefore evaluated against
 * the amount the customer actually pays, not against a line item.
 */
export function quoteAsMerchantProduct(quote: SignedQuote): MerchantProduct {
  return {
    id: quote.quoteId,
    merchant_id: quote.merchantId,
    name: `AutoParts order ${quote.merchantOrderRef}`,
    category: quote.agentPayCategory,
    price_cents: quote.totalCents,
    currency: quote.currency,
  };
}

/**
 * SDK LIMITATION (documented, worked around at the integration seam)
 *
 * `createAgentPayCheckoutHandler` fetches the registry verification key with
 * `cache: "force-cache"`. Inside a Next.js server that pins AgentPay's public
 * key in the data cache with no revalidation, so a key rotation on AgentPay's
 * side would make every mandate signature fail until the cache is dropped.
 * This was reproduced end to end: after the registry rotated its key, every
 * verification returned MANDATE_SIGNATURE_INVALID.
 *
 * The SDK accepts an injected `fetcher`, which is the supported seam, so the
 * store overrides the cache directive for that one endpoint. Nothing else about
 * the request is touched.
 *
 * Requested SDK change: fetch the registry key with a bounded revalidation
 * window (it is already served with `cache-control: public, max-age=3600`)
 * rather than `force-cache`.
 */
export function withFreshRegistryKeys(fetcher: typeof fetch): typeof fetch {
  return async (input, init) => {
    const href =
      typeof input === "string" ? input : input instanceof URL ? input.href : input.url;
    if (new URL(href).pathname === "/api/registry/keys") {
      return fetcher(input, { ...init, cache: "no-store" });
    }
    return fetcher(input, init);
  };
}

export type VerificationOutcome =
  | (MerchantCheckoutResult & { kind: "decision"; httpStatus: number })
  | { kind: "rejected_payload"; httpStatus: number; reason: string };

/**
 * Runs the SDK's verification over an agent request.
 *
 * The SDK performs, against AgentPay's live registry: agent identity lookup,
 * Ed25519 request-signature verification over method/path/body-hash/timestamp/
 * nonce, the 60 second signing window, single-use nonce consumption, registry
 * mandate-signature verification, agent/mandate binding, live mandate status,
 * and the deterministic merchant/category/currency/amount/uses policy.
 */
export async function verifyWithAgentPay(input: {
  request: Request;
  rawBody: string;
  quote: SignedQuote;
  identity?: MerchantIdentity;
  fetcher?: typeof fetch;
  now?: () => Date;
}): Promise<VerificationOutcome> {
  const identity = input.identity ?? merchantIdentity();

  const handler = createAgentPayCheckoutHandler({
    merchantId: identity.merchantId,
    registryUrl: identity.registryUrl,
    resolveProduct: async (productId) =>
      productId === input.quote.quoteId ? quoteAsMerchantProduct(input.quote) : null,
    fetcher: withFreshRegistryKeys(input.fetcher ?? fetch),
    ...(input.now ? { now: input.now } : {}),
  });

  // The SDK reads the body itself and verifies the signature over those exact
  // bytes, so it receives a faithful copy of the original request.
  const replayed = new Request(input.request.url, {
    method: input.request.method,
    headers: input.request.headers,
    body: input.rawBody,
  });

  const response = await handler(replayed);
  const payload = (await response.json()) as MerchantCheckoutResult | { error: string };

  if (!("decision" in payload)) {
    // The SDK refused the request before reaching a policy decision (an
    // unparseable checkout body or an unresolvable product). Surfacing this as
    // a refusal would misreport a client error as a mandate outcome.
    return {
      kind: "rejected_payload",
      httpStatus: response.status,
      reason: typeof payload.error === "string" ? payload.error : "The checkout request was rejected.",
    };
  }

  return { ...payload, kind: "decision", httpStatus: response.status };
}
